# Generated by Django 5.2.10 on 2026-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(max_length=100)),
                ('income_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('trust_score', models.IntegerField(default=0)),
                ('red_flags', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('VERIFIED', 'Verified Safe'), ('SCAM', 'Potential Scam')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
