# Generated by Django 5.2.10 on 2026-02-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('trust_score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('security_flags', models.JSONField(default=list)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('info_paragraph', models.TextField()),
                ('documents_required', models.JSONField(default=list)),
                ('added_from', models.CharField(default='RSS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='agent.scholarshipcategory')),
            ],
        ),
    ]
